Started at 2020-12-08 15:21:29
 
 -------------- celery@WIN-LBEUVJDAK3Q v5.0.2 (singularity)
--- ***** ----- 
-- ******* ---- Linux-4.19.84-microsoft-standard-x86_64-with-Ubuntu-18.04-bionic 2020-12-08 15:21:30
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         backend.main:0x7f7139ae6390
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     redis://localhost:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . backend.main.tasks.accumulate_time

[2020-12-08 15:21:30,599: INFO/MainProcess] Connected to redis://localhost:6379//
[2020-12-08 15:21:30,614: INFO/MainProcess] mingle: searching for neighbors
[2020-12-08 15:21:31,631: INFO/MainProcess] mingle: all alone
[2020-12-08 15:21:31,653: INFO/MainProcess] celery@WIN-LBEUVJDAK3Q ready.
[2020-12-08 15:21:42,988: INFO/MainProcess] Received task: backend.main.tasks.accumulate_time[b4c4b2fb-c1f1-4888-8cf4-c1fa0419d987]  
**** The executable "caRepeater" couldn't be located
**** because of errno = "No such file or directory".
**** You may need to modify your PATH environment variable.
**** Unable to start "CA Repeater" process.
[2020-12-08 15:22:16,116: INFO/ForkPoolWorker-1] Task backend.main.tasks.accumulate_time[b4c4b2fb-c1f1-4888-8cf4-c1fa0419d987] succeeded in 33.125563699999475s: None

worker: Warm shutdown (MainProcess)

worker: Warm shutdown (MainProcess)
